print("Calificaciones matemáticas: ")
me=float(input("Calificación examen final: "))
m1=float(input("Calificación tarea 1: "))
m2=float(input("Calificación tarea 2: "))
m3=float(input("Calificación tarea 3: "))
print("Calificaciones física: ")
fe=float(input("Calificación examen final: "))
f1=float(input("Calificación tarea 1: "))
f2=float(input("Calificación tarea 2: "))
print("Calificaciones química: ")
qe=float(input("Calificación examen final: "))
q1=float(input("Calificación tarea 1: "))
q2=float(input("Calificación tarea 2: "))
q3=float(input("Calificación tarea 3: "))
mat=(me*0.90)+(((m1+m2+m3)/3)*0.10)
fis=(fe*0.80)+(((f1+f2)/2)*0.20)
qui=(qe*0.85)+(((q1+q2+q3)/3)*0.15)
pg=(mat+fis+qui)/3
print("Promedio general: ",pg)
print("Promedio general matemáticas: ",mat)
print("Promedio general física: ",fis)
print("Promedio general química: ",qui)